// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raw_proteins.proto

package edu.hyu.cs.pb;

public final class RawProteinsPB {
  private RawProteinsPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProteinOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string name = 1;
    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional int32 id = 2;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * In a file of records of type Protein ids will
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * In a file of records of type Protein ids will
     * </pre>
     */
    int getId();

    // optional string residues = 3;
    /**
     * <code>optional string residues = 3;</code>
     *
     * <pre>
     * usually be numbered sequentially.
     * </pre>
     */
    boolean hasResidues();
    /**
     * <code>optional string residues = 3;</code>
     *
     * <pre>
     * usually be numbered sequentially.
     * </pre>
     */
    java.lang.String getResidues();
    /**
     * <code>optional string residues = 3;</code>
     *
     * <pre>
     * usually be numbered sequentially.
     * </pre>
     */
    com.google.protobuf.ByteString
        getResiduesBytes();

    // optional int32 target_pos = 5;
    /**
     * <code>optional int32 target_pos = 5;</code>
     *
     * <pre>
     * Index in target protein that this decoy protein is from
     * </pre>
     */
    boolean hasTargetPos();
    /**
     * <code>optional int32 target_pos = 5;</code>
     *
     * <pre>
     * Index in target protein that this decoy protein is from
     * </pre>
     */
    int getTargetPos();
  }
  /**
   * Protobuf type {@code pb.Protein}
   */
  public static final class Protein extends
      com.google.protobuf.GeneratedMessage
      implements ProteinOrBuilder {
    // Use Protein.newBuilder() to construct.
    private Protein(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Protein(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Protein defaultInstance;
    public static Protein getDefaultInstance() {
      return defaultInstance;
    }

    public Protein getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Protein(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              residues_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              targetPos_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.hyu.cs.pb.RawProteinsPB.internal_static_pb_Protein_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.hyu.cs.pb.RawProteinsPB.internal_static_pb_Protein_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.hyu.cs.pb.RawProteinsPB.Protein.class, edu.hyu.cs.pb.RawProteinsPB.Protein.Builder.class);
    }

    public static com.google.protobuf.Parser<Protein> PARSER =
        new com.google.protobuf.AbstractParser<Protein>() {
      public Protein parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Protein(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Protein> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * In a file of records of type Protein ids will
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * In a file of records of type Protein ids will
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // optional string residues = 3;
    public static final int RESIDUES_FIELD_NUMBER = 3;
    private java.lang.Object residues_;
    /**
     * <code>optional string residues = 3;</code>
     *
     * <pre>
     * usually be numbered sequentially.
     * </pre>
     */
    public boolean hasResidues() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string residues = 3;</code>
     *
     * <pre>
     * usually be numbered sequentially.
     * </pre>
     */
    public java.lang.String getResidues() {
      java.lang.Object ref = residues_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          residues_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string residues = 3;</code>
     *
     * <pre>
     * usually be numbered sequentially.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResiduesBytes() {
      java.lang.Object ref = residues_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        residues_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 target_pos = 5;
    public static final int TARGET_POS_FIELD_NUMBER = 5;
    private int targetPos_;
    /**
     * <code>optional int32 target_pos = 5;</code>
     *
     * <pre>
     * Index in target protein that this decoy protein is from
     * </pre>
     */
    public boolean hasTargetPos() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 target_pos = 5;</code>
     *
     * <pre>
     * Index in target protein that this decoy protein is from
     * </pre>
     */
    public int getTargetPos() {
      return targetPos_;
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      residues_ = "";
      targetPos_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getResiduesBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, targetPos_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getResiduesBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, targetPos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.RawProteinsPB.Protein parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.hyu.cs.pb.RawProteinsPB.Protein prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.Protein}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.hyu.cs.pb.RawProteinsPB.ProteinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.hyu.cs.pb.RawProteinsPB.internal_static_pb_Protein_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.hyu.cs.pb.RawProteinsPB.internal_static_pb_Protein_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.hyu.cs.pb.RawProteinsPB.Protein.class, edu.hyu.cs.pb.RawProteinsPB.Protein.Builder.class);
      }

      // Construct using edu.hyu.cs.pb.RawProteinsPB.Protein.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        residues_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        targetPos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.hyu.cs.pb.RawProteinsPB.internal_static_pb_Protein_descriptor;
      }

      public edu.hyu.cs.pb.RawProteinsPB.Protein getDefaultInstanceForType() {
        return edu.hyu.cs.pb.RawProteinsPB.Protein.getDefaultInstance();
      }

      public edu.hyu.cs.pb.RawProteinsPB.Protein build() {
        edu.hyu.cs.pb.RawProteinsPB.Protein result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.hyu.cs.pb.RawProteinsPB.Protein buildPartial() {
        edu.hyu.cs.pb.RawProteinsPB.Protein result = new edu.hyu.cs.pb.RawProteinsPB.Protein(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.residues_ = residues_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.targetPos_ = targetPos_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.hyu.cs.pb.RawProteinsPB.Protein) {
          return mergeFrom((edu.hyu.cs.pb.RawProteinsPB.Protein)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.hyu.cs.pb.RawProteinsPB.Protein other) {
        if (other == edu.hyu.cs.pb.RawProteinsPB.Protein.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasResidues()) {
          bitField0_ |= 0x00000004;
          residues_ = other.residues_;
          onChanged();
        }
        if (other.hasTargetPos()) {
          setTargetPos(other.getTargetPos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.hyu.cs.pb.RawProteinsPB.Protein parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.hyu.cs.pb.RawProteinsPB.Protein) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional int32 id = 2;
      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * In a file of records of type Protein ids will
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * In a file of records of type Protein ids will
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * In a file of records of type Protein ids will
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * In a file of records of type Protein ids will
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string residues = 3;
      private java.lang.Object residues_ = "";
      /**
       * <code>optional string residues = 3;</code>
       *
       * <pre>
       * usually be numbered sequentially.
       * </pre>
       */
      public boolean hasResidues() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string residues = 3;</code>
       *
       * <pre>
       * usually be numbered sequentially.
       * </pre>
       */
      public java.lang.String getResidues() {
        java.lang.Object ref = residues_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          residues_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string residues = 3;</code>
       *
       * <pre>
       * usually be numbered sequentially.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResiduesBytes() {
        java.lang.Object ref = residues_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          residues_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string residues = 3;</code>
       *
       * <pre>
       * usually be numbered sequentially.
       * </pre>
       */
      public Builder setResidues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        residues_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string residues = 3;</code>
       *
       * <pre>
       * usually be numbered sequentially.
       * </pre>
       */
      public Builder clearResidues() {
        bitField0_ = (bitField0_ & ~0x00000004);
        residues_ = getDefaultInstance().getResidues();
        onChanged();
        return this;
      }
      /**
       * <code>optional string residues = 3;</code>
       *
       * <pre>
       * usually be numbered sequentially.
       * </pre>
       */
      public Builder setResiduesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        residues_ = value;
        onChanged();
        return this;
      }

      // optional int32 target_pos = 5;
      private int targetPos_ ;
      /**
       * <code>optional int32 target_pos = 5;</code>
       *
       * <pre>
       * Index in target protein that this decoy protein is from
       * </pre>
       */
      public boolean hasTargetPos() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 target_pos = 5;</code>
       *
       * <pre>
       * Index in target protein that this decoy protein is from
       * </pre>
       */
      public int getTargetPos() {
        return targetPos_;
      }
      /**
       * <code>optional int32 target_pos = 5;</code>
       *
       * <pre>
       * Index in target protein that this decoy protein is from
       * </pre>
       */
      public Builder setTargetPos(int value) {
        bitField0_ |= 0x00000008;
        targetPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 target_pos = 5;</code>
       *
       * <pre>
       * Index in target protein that this decoy protein is from
       * </pre>
       */
      public Builder clearTargetPos() {
        bitField0_ = (bitField0_ & ~0x00000008);
        targetPos_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.Protein)
    }

    static {
      defaultInstance = new Protein(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.Protein)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Protein_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_Protein_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022raw_proteins.proto\022\002pb\"I\n\007Protein\022\014\n\004n" +
      "ame\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\020\n\010residues\030\003 \001(\t\022" +
      "\022\n\ntarget_pos\030\005 \001(\005B \n\redu.hyu.cs.pbB\rRa" +
      "wProteinsPBH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pb_Protein_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pb_Protein_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_Protein_descriptor,
              new java.lang.String[] { "Name", "Id", "Residues", "TargetPos", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
