// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: results.proto

package edu.hyu.cs.pb;

public final class ResultsPB {
  private ResultsPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MatchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional double xcorr = 1;
    /**
     * <code>optional double xcorr = 1;</code>
     */
    boolean hasXcorr();
    /**
     * <code>optional double xcorr = 1;</code>
     */
    double getXcorr();

    // optional .Peptide peptide = 2;
    /**
     * <code>optional .Peptide peptide = 2;</code>
     */
    boolean hasPeptide();
    /**
     * <code>optional .Peptide peptide = 2;</code>
     */
    edu.hyu.cs.pb.PeptidesPB.Peptide getPeptide();
    /**
     * <code>optional .Peptide peptide = 2;</code>
     */
    edu.hyu.cs.pb.PeptidesPB.PeptideOrBuilder getPeptideOrBuilder();
  }
  /**
   * Protobuf type {@code Match}
   */
  public static final class Match extends
      com.google.protobuf.GeneratedMessage
      implements MatchOrBuilder {
    // Use Match.newBuilder() to construct.
    private Match(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Match(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Match defaultInstance;
    public static Match getDefaultInstance() {
      return defaultInstance;
    }

    public Match getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Match(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              xcorr_ = input.readDouble();
              break;
            }
            case 18: {
              edu.hyu.cs.pb.PeptidesPB.Peptide.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = peptide_.toBuilder();
              }
              peptide_ = input.readMessage(edu.hyu.cs.pb.PeptidesPB.Peptide.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(peptide_);
                peptide_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.hyu.cs.pb.ResultsPB.internal_static_Match_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.hyu.cs.pb.ResultsPB.internal_static_Match_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.hyu.cs.pb.ResultsPB.Match.class, edu.hyu.cs.pb.ResultsPB.Match.Builder.class);
    }

    public static com.google.protobuf.Parser<Match> PARSER =
        new com.google.protobuf.AbstractParser<Match>() {
      public Match parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Match(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Match> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional double xcorr = 1;
    public static final int XCORR_FIELD_NUMBER = 1;
    private double xcorr_;
    /**
     * <code>optional double xcorr = 1;</code>
     */
    public boolean hasXcorr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double xcorr = 1;</code>
     */
    public double getXcorr() {
      return xcorr_;
    }

    // optional .Peptide peptide = 2;
    public static final int PEPTIDE_FIELD_NUMBER = 2;
    private edu.hyu.cs.pb.PeptidesPB.Peptide peptide_;
    /**
     * <code>optional .Peptide peptide = 2;</code>
     */
    public boolean hasPeptide() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Peptide peptide = 2;</code>
     */
    public edu.hyu.cs.pb.PeptidesPB.Peptide getPeptide() {
      return peptide_;
    }
    /**
     * <code>optional .Peptide peptide = 2;</code>
     */
    public edu.hyu.cs.pb.PeptidesPB.PeptideOrBuilder getPeptideOrBuilder() {
      return peptide_;
    }

    private void initFields() {
      xcorr_ = 0D;
      peptide_ = edu.hyu.cs.pb.PeptidesPB.Peptide.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, xcorr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, peptide_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, xcorr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, peptide_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Match parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.hyu.cs.pb.ResultsPB.Match prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Match}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.hyu.cs.pb.ResultsPB.MatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Match_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Match_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.hyu.cs.pb.ResultsPB.Match.class, edu.hyu.cs.pb.ResultsPB.Match.Builder.class);
      }

      // Construct using edu.hyu.cs.pb.ResultsPB.Match.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPeptideFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        xcorr_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (peptideBuilder_ == null) {
          peptide_ = edu.hyu.cs.pb.PeptidesPB.Peptide.getDefaultInstance();
        } else {
          peptideBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Match_descriptor;
      }

      public edu.hyu.cs.pb.ResultsPB.Match getDefaultInstanceForType() {
        return edu.hyu.cs.pb.ResultsPB.Match.getDefaultInstance();
      }

      public edu.hyu.cs.pb.ResultsPB.Match build() {
        edu.hyu.cs.pb.ResultsPB.Match result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.hyu.cs.pb.ResultsPB.Match buildPartial() {
        edu.hyu.cs.pb.ResultsPB.Match result = new edu.hyu.cs.pb.ResultsPB.Match(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.xcorr_ = xcorr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (peptideBuilder_ == null) {
          result.peptide_ = peptide_;
        } else {
          result.peptide_ = peptideBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.hyu.cs.pb.ResultsPB.Match) {
          return mergeFrom((edu.hyu.cs.pb.ResultsPB.Match)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.hyu.cs.pb.ResultsPB.Match other) {
        if (other == edu.hyu.cs.pb.ResultsPB.Match.getDefaultInstance()) return this;
        if (other.hasXcorr()) {
          setXcorr(other.getXcorr());
        }
        if (other.hasPeptide()) {
          mergePeptide(other.getPeptide());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.hyu.cs.pb.ResultsPB.Match parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.hyu.cs.pb.ResultsPB.Match) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double xcorr = 1;
      private double xcorr_ ;
      /**
       * <code>optional double xcorr = 1;</code>
       */
      public boolean hasXcorr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double xcorr = 1;</code>
       */
      public double getXcorr() {
        return xcorr_;
      }
      /**
       * <code>optional double xcorr = 1;</code>
       */
      public Builder setXcorr(double value) {
        bitField0_ |= 0x00000001;
        xcorr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double xcorr = 1;</code>
       */
      public Builder clearXcorr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        xcorr_ = 0D;
        onChanged();
        return this;
      }

      // optional .Peptide peptide = 2;
      private edu.hyu.cs.pb.PeptidesPB.Peptide peptide_ = edu.hyu.cs.pb.PeptidesPB.Peptide.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.hyu.cs.pb.PeptidesPB.Peptide, edu.hyu.cs.pb.PeptidesPB.Peptide.Builder, edu.hyu.cs.pb.PeptidesPB.PeptideOrBuilder> peptideBuilder_;
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public boolean hasPeptide() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public edu.hyu.cs.pb.PeptidesPB.Peptide getPeptide() {
        if (peptideBuilder_ == null) {
          return peptide_;
        } else {
          return peptideBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public Builder setPeptide(edu.hyu.cs.pb.PeptidesPB.Peptide value) {
        if (peptideBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          peptide_ = value;
          onChanged();
        } else {
          peptideBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public Builder setPeptide(
          edu.hyu.cs.pb.PeptidesPB.Peptide.Builder builderForValue) {
        if (peptideBuilder_ == null) {
          peptide_ = builderForValue.build();
          onChanged();
        } else {
          peptideBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public Builder mergePeptide(edu.hyu.cs.pb.PeptidesPB.Peptide value) {
        if (peptideBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              peptide_ != edu.hyu.cs.pb.PeptidesPB.Peptide.getDefaultInstance()) {
            peptide_ =
              edu.hyu.cs.pb.PeptidesPB.Peptide.newBuilder(peptide_).mergeFrom(value).buildPartial();
          } else {
            peptide_ = value;
          }
          onChanged();
        } else {
          peptideBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public Builder clearPeptide() {
        if (peptideBuilder_ == null) {
          peptide_ = edu.hyu.cs.pb.PeptidesPB.Peptide.getDefaultInstance();
          onChanged();
        } else {
          peptideBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public edu.hyu.cs.pb.PeptidesPB.Peptide.Builder getPeptideBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPeptideFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      public edu.hyu.cs.pb.PeptidesPB.PeptideOrBuilder getPeptideOrBuilder() {
        if (peptideBuilder_ != null) {
          return peptideBuilder_.getMessageOrBuilder();
        } else {
          return peptide_;
        }
      }
      /**
       * <code>optional .Peptide peptide = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.hyu.cs.pb.PeptidesPB.Peptide, edu.hyu.cs.pb.PeptidesPB.Peptide.Builder, edu.hyu.cs.pb.PeptidesPB.PeptideOrBuilder> 
          getPeptideFieldBuilder() {
        if (peptideBuilder_ == null) {
          peptideBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.hyu.cs.pb.PeptidesPB.Peptide, edu.hyu.cs.pb.PeptidesPB.Peptide.Builder, edu.hyu.cs.pb.PeptidesPB.PeptideOrBuilder>(
                  peptide_,
                  getParentForChildren(),
                  isClean());
          peptide_ = null;
        }
        return peptideBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Match)
    }

    static {
      defaultInstance = new Match(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Match)
  }

  public interface StatsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 count = 1;
    /**
     * <code>optional int32 count = 1;</code>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 1;</code>
     */
    int getCount();

    // optional double sum = 2;
    /**
     * <code>optional double sum = 2;</code>
     */
    boolean hasSum();
    /**
     * <code>optional double sum = 2;</code>
     */
    double getSum();

    // optional double sum_squares = 3;
    /**
     * <code>optional double sum_squares = 3;</code>
     */
    boolean hasSumSquares();
    /**
     * <code>optional double sum_squares = 3;</code>
     */
    double getSumSquares();
  }
  /**
   * Protobuf type {@code Stats}
   */
  public static final class Stats extends
      com.google.protobuf.GeneratedMessage
      implements StatsOrBuilder {
    // Use Stats.newBuilder() to construct.
    private Stats(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Stats(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Stats defaultInstance;
    public static Stats getDefaultInstance() {
      return defaultInstance;
    }

    public Stats getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Stats(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              sum_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              sumSquares_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.hyu.cs.pb.ResultsPB.internal_static_Stats_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.hyu.cs.pb.ResultsPB.internal_static_Stats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.hyu.cs.pb.ResultsPB.Stats.class, edu.hyu.cs.pb.ResultsPB.Stats.Builder.class);
    }

    public static com.google.protobuf.Parser<Stats> PARSER =
        new com.google.protobuf.AbstractParser<Stats>() {
      public Stats parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stats(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Stats> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 count = 1;
    public static final int COUNT_FIELD_NUMBER = 1;
    private int count_;
    /**
     * <code>optional int32 count = 1;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 count = 1;</code>
     */
    public int getCount() {
      return count_;
    }

    // optional double sum = 2;
    public static final int SUM_FIELD_NUMBER = 2;
    private double sum_;
    /**
     * <code>optional double sum = 2;</code>
     */
    public boolean hasSum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double sum = 2;</code>
     */
    public double getSum() {
      return sum_;
    }

    // optional double sum_squares = 3;
    public static final int SUM_SQUARES_FIELD_NUMBER = 3;
    private double sumSquares_;
    /**
     * <code>optional double sum_squares = 3;</code>
     */
    public boolean hasSumSquares() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double sum_squares = 3;</code>
     */
    public double getSumSquares() {
      return sumSquares_;
    }

    private void initFields() {
      count_ = 0;
      sum_ = 0D;
      sumSquares_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, sum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, sumSquares_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, count_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, sum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, sumSquares_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Stats parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.hyu.cs.pb.ResultsPB.Stats prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Stats}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.hyu.cs.pb.ResultsPB.StatsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Stats_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Stats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.hyu.cs.pb.ResultsPB.Stats.class, edu.hyu.cs.pb.ResultsPB.Stats.Builder.class);
      }

      // Construct using edu.hyu.cs.pb.ResultsPB.Stats.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sum_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        sumSquares_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Stats_descriptor;
      }

      public edu.hyu.cs.pb.ResultsPB.Stats getDefaultInstanceForType() {
        return edu.hyu.cs.pb.ResultsPB.Stats.getDefaultInstance();
      }

      public edu.hyu.cs.pb.ResultsPB.Stats build() {
        edu.hyu.cs.pb.ResultsPB.Stats result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.hyu.cs.pb.ResultsPB.Stats buildPartial() {
        edu.hyu.cs.pb.ResultsPB.Stats result = new edu.hyu.cs.pb.ResultsPB.Stats(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sum_ = sum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sumSquares_ = sumSquares_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.hyu.cs.pb.ResultsPB.Stats) {
          return mergeFrom((edu.hyu.cs.pb.ResultsPB.Stats)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.hyu.cs.pb.ResultsPB.Stats other) {
        if (other == edu.hyu.cs.pb.ResultsPB.Stats.getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasSum()) {
          setSum(other.getSum());
        }
        if (other.hasSumSquares()) {
          setSumSquares(other.getSumSquares());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.hyu.cs.pb.ResultsPB.Stats parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.hyu.cs.pb.ResultsPB.Stats) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 count = 1;
      private int count_ ;
      /**
       * <code>optional int32 count = 1;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 count = 1;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 1;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 1;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        onChanged();
        return this;
      }

      // optional double sum = 2;
      private double sum_ ;
      /**
       * <code>optional double sum = 2;</code>
       */
      public boolean hasSum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double sum = 2;</code>
       */
      public double getSum() {
        return sum_;
      }
      /**
       * <code>optional double sum = 2;</code>
       */
      public Builder setSum(double value) {
        bitField0_ |= 0x00000002;
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double sum = 2;</code>
       */
      public Builder clearSum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sum_ = 0D;
        onChanged();
        return this;
      }

      // optional double sum_squares = 3;
      private double sumSquares_ ;
      /**
       * <code>optional double sum_squares = 3;</code>
       */
      public boolean hasSumSquares() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double sum_squares = 3;</code>
       */
      public double getSumSquares() {
        return sumSquares_;
      }
      /**
       * <code>optional double sum_squares = 3;</code>
       */
      public Builder setSumSquares(double value) {
        bitField0_ |= 0x00000004;
        sumSquares_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double sum_squares = 3;</code>
       */
      public Builder clearSumSquares() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sumSquares_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Stats)
    }

    static {
      defaultInstance = new Stats(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Stats)
  }

  public interface ResultsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .Spectrum spectrum = 1;
    /**
     * <code>optional .Spectrum spectrum = 1;</code>
     */
    boolean hasSpectrum();
    /**
     * <code>optional .Spectrum spectrum = 1;</code>
     */
    edu.hyu.cs.pb.SpectrumsPB.Spectrum getSpectrum();
    /**
     * <code>optional .Spectrum spectrum = 1;</code>
     */
    edu.hyu.cs.pb.SpectrumsPB.SpectrumOrBuilder getSpectrumOrBuilder();

    // optional int32 charge = 2;
    /**
     * <code>optional int32 charge = 2;</code>
     */
    boolean hasCharge();
    /**
     * <code>optional int32 charge = 2;</code>
     */
    int getCharge();

    // repeated .Match matches = 3;
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    java.util.List<edu.hyu.cs.pb.ResultsPB.Match> 
        getMatchesList();
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    edu.hyu.cs.pb.ResultsPB.Match getMatches(int index);
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    int getMatchesCount();
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    java.util.List<? extends edu.hyu.cs.pb.ResultsPB.MatchOrBuilder> 
        getMatchesOrBuilderList();
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    edu.hyu.cs.pb.ResultsPB.MatchOrBuilder getMatchesOrBuilder(
        int index);

    // optional int32 spectrum_index = 4;
    /**
     * <code>optional int32 spectrum_index = 4;</code>
     */
    boolean hasSpectrumIndex();
    /**
     * <code>optional int32 spectrum_index = 4;</code>
     */
    int getSpectrumIndex();

    // optional .Stats stats = 5;
    /**
     * <code>optional .Stats stats = 5;</code>
     */
    boolean hasStats();
    /**
     * <code>optional .Stats stats = 5;</code>
     */
    edu.hyu.cs.pb.ResultsPB.Stats getStats();
    /**
     * <code>optional .Stats stats = 5;</code>
     */
    edu.hyu.cs.pb.ResultsPB.StatsOrBuilder getStatsOrBuilder();
  }
  /**
   * Protobuf type {@code Results}
   */
  public static final class Results extends
      com.google.protobuf.GeneratedMessage
      implements ResultsOrBuilder {
    // Use Results.newBuilder() to construct.
    private Results(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Results(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Results defaultInstance;
    public static Results getDefaultInstance() {
      return defaultInstance;
    }

    public Results getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Results(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              edu.hyu.cs.pb.SpectrumsPB.Spectrum.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = spectrum_.toBuilder();
              }
              spectrum_ = input.readMessage(edu.hyu.cs.pb.SpectrumsPB.Spectrum.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(spectrum_);
                spectrum_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              charge_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                matches_ = new java.util.ArrayList<edu.hyu.cs.pb.ResultsPB.Match>();
                mutable_bitField0_ |= 0x00000004;
              }
              matches_.add(input.readMessage(edu.hyu.cs.pb.ResultsPB.Match.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              spectrumIndex_ = input.readInt32();
              break;
            }
            case 42: {
              edu.hyu.cs.pb.ResultsPB.Stats.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = stats_.toBuilder();
              }
              stats_ = input.readMessage(edu.hyu.cs.pb.ResultsPB.Stats.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stats_);
                stats_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          matches_ = java.util.Collections.unmodifiableList(matches_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.hyu.cs.pb.ResultsPB.internal_static_Results_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.hyu.cs.pb.ResultsPB.internal_static_Results_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.hyu.cs.pb.ResultsPB.Results.class, edu.hyu.cs.pb.ResultsPB.Results.Builder.class);
    }

    public static com.google.protobuf.Parser<Results> PARSER =
        new com.google.protobuf.AbstractParser<Results>() {
      public Results parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Results(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Results> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .Spectrum spectrum = 1;
    public static final int SPECTRUM_FIELD_NUMBER = 1;
    private edu.hyu.cs.pb.SpectrumsPB.Spectrum spectrum_;
    /**
     * <code>optional .Spectrum spectrum = 1;</code>
     */
    public boolean hasSpectrum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Spectrum spectrum = 1;</code>
     */
    public edu.hyu.cs.pb.SpectrumsPB.Spectrum getSpectrum() {
      return spectrum_;
    }
    /**
     * <code>optional .Spectrum spectrum = 1;</code>
     */
    public edu.hyu.cs.pb.SpectrumsPB.SpectrumOrBuilder getSpectrumOrBuilder() {
      return spectrum_;
    }

    // optional int32 charge = 2;
    public static final int CHARGE_FIELD_NUMBER = 2;
    private int charge_;
    /**
     * <code>optional int32 charge = 2;</code>
     */
    public boolean hasCharge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 charge = 2;</code>
     */
    public int getCharge() {
      return charge_;
    }

    // repeated .Match matches = 3;
    public static final int MATCHES_FIELD_NUMBER = 3;
    private java.util.List<edu.hyu.cs.pb.ResultsPB.Match> matches_;
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    public java.util.List<edu.hyu.cs.pb.ResultsPB.Match> getMatchesList() {
      return matches_;
    }
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    public java.util.List<? extends edu.hyu.cs.pb.ResultsPB.MatchOrBuilder> 
        getMatchesOrBuilderList() {
      return matches_;
    }
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    public int getMatchesCount() {
      return matches_.size();
    }
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    public edu.hyu.cs.pb.ResultsPB.Match getMatches(int index) {
      return matches_.get(index);
    }
    /**
     * <code>repeated .Match matches = 3;</code>
     */
    public edu.hyu.cs.pb.ResultsPB.MatchOrBuilder getMatchesOrBuilder(
        int index) {
      return matches_.get(index);
    }

    // optional int32 spectrum_index = 4;
    public static final int SPECTRUM_INDEX_FIELD_NUMBER = 4;
    private int spectrumIndex_;
    /**
     * <code>optional int32 spectrum_index = 4;</code>
     */
    public boolean hasSpectrumIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 spectrum_index = 4;</code>
     */
    public int getSpectrumIndex() {
      return spectrumIndex_;
    }

    // optional .Stats stats = 5;
    public static final int STATS_FIELD_NUMBER = 5;
    private edu.hyu.cs.pb.ResultsPB.Stats stats_;
    /**
     * <code>optional .Stats stats = 5;</code>
     */
    public boolean hasStats() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Stats stats = 5;</code>
     */
    public edu.hyu.cs.pb.ResultsPB.Stats getStats() {
      return stats_;
    }
    /**
     * <code>optional .Stats stats = 5;</code>
     */
    public edu.hyu.cs.pb.ResultsPB.StatsOrBuilder getStatsOrBuilder() {
      return stats_;
    }

    private void initFields() {
      spectrum_ = edu.hyu.cs.pb.SpectrumsPB.Spectrum.getDefaultInstance();
      charge_ = 0;
      matches_ = java.util.Collections.emptyList();
      spectrumIndex_ = 0;
      stats_ = edu.hyu.cs.pb.ResultsPB.Stats.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, spectrum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, charge_);
      }
      for (int i = 0; i < matches_.size(); i++) {
        output.writeMessage(3, matches_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, spectrumIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, stats_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, spectrum_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, charge_);
      }
      for (int i = 0; i < matches_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, matches_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, spectrumIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, stats_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ResultsPB.Results parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.hyu.cs.pb.ResultsPB.Results prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Results}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.hyu.cs.pb.ResultsPB.ResultsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Results_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Results_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.hyu.cs.pb.ResultsPB.Results.class, edu.hyu.cs.pb.ResultsPB.Results.Builder.class);
      }

      // Construct using edu.hyu.cs.pb.ResultsPB.Results.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSpectrumFieldBuilder();
          getMatchesFieldBuilder();
          getStatsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (spectrumBuilder_ == null) {
          spectrum_ = edu.hyu.cs.pb.SpectrumsPB.Spectrum.getDefaultInstance();
        } else {
          spectrumBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        charge_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          matchesBuilder_.clear();
        }
        spectrumIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (statsBuilder_ == null) {
          stats_ = edu.hyu.cs.pb.ResultsPB.Stats.getDefaultInstance();
        } else {
          statsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.hyu.cs.pb.ResultsPB.internal_static_Results_descriptor;
      }

      public edu.hyu.cs.pb.ResultsPB.Results getDefaultInstanceForType() {
        return edu.hyu.cs.pb.ResultsPB.Results.getDefaultInstance();
      }

      public edu.hyu.cs.pb.ResultsPB.Results build() {
        edu.hyu.cs.pb.ResultsPB.Results result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.hyu.cs.pb.ResultsPB.Results buildPartial() {
        edu.hyu.cs.pb.ResultsPB.Results result = new edu.hyu.cs.pb.ResultsPB.Results(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (spectrumBuilder_ == null) {
          result.spectrum_ = spectrum_;
        } else {
          result.spectrum_ = spectrumBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.charge_ = charge_;
        if (matchesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            matches_ = java.util.Collections.unmodifiableList(matches_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.matches_ = matches_;
        } else {
          result.matches_ = matchesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.spectrumIndex_ = spectrumIndex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        if (statsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = statsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.hyu.cs.pb.ResultsPB.Results) {
          return mergeFrom((edu.hyu.cs.pb.ResultsPB.Results)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.hyu.cs.pb.ResultsPB.Results other) {
        if (other == edu.hyu.cs.pb.ResultsPB.Results.getDefaultInstance()) return this;
        if (other.hasSpectrum()) {
          mergeSpectrum(other.getSpectrum());
        }
        if (other.hasCharge()) {
          setCharge(other.getCharge());
        }
        if (matchesBuilder_ == null) {
          if (!other.matches_.isEmpty()) {
            if (matches_.isEmpty()) {
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMatchesIsMutable();
              matches_.addAll(other.matches_);
            }
            onChanged();
          }
        } else {
          if (!other.matches_.isEmpty()) {
            if (matchesBuilder_.isEmpty()) {
              matchesBuilder_.dispose();
              matchesBuilder_ = null;
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000004);
              matchesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMatchesFieldBuilder() : null;
            } else {
              matchesBuilder_.addAllMessages(other.matches_);
            }
          }
        }
        if (other.hasSpectrumIndex()) {
          setSpectrumIndex(other.getSpectrumIndex());
        }
        if (other.hasStats()) {
          mergeStats(other.getStats());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.hyu.cs.pb.ResultsPB.Results parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.hyu.cs.pb.ResultsPB.Results) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .Spectrum spectrum = 1;
      private edu.hyu.cs.pb.SpectrumsPB.Spectrum spectrum_ = edu.hyu.cs.pb.SpectrumsPB.Spectrum.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.hyu.cs.pb.SpectrumsPB.Spectrum, edu.hyu.cs.pb.SpectrumsPB.Spectrum.Builder, edu.hyu.cs.pb.SpectrumsPB.SpectrumOrBuilder> spectrumBuilder_;
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public boolean hasSpectrum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public edu.hyu.cs.pb.SpectrumsPB.Spectrum getSpectrum() {
        if (spectrumBuilder_ == null) {
          return spectrum_;
        } else {
          return spectrumBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public Builder setSpectrum(edu.hyu.cs.pb.SpectrumsPB.Spectrum value) {
        if (spectrumBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          spectrum_ = value;
          onChanged();
        } else {
          spectrumBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public Builder setSpectrum(
          edu.hyu.cs.pb.SpectrumsPB.Spectrum.Builder builderForValue) {
        if (spectrumBuilder_ == null) {
          spectrum_ = builderForValue.build();
          onChanged();
        } else {
          spectrumBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public Builder mergeSpectrum(edu.hyu.cs.pb.SpectrumsPB.Spectrum value) {
        if (spectrumBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              spectrum_ != edu.hyu.cs.pb.SpectrumsPB.Spectrum.getDefaultInstance()) {
            spectrum_ =
              edu.hyu.cs.pb.SpectrumsPB.Spectrum.newBuilder(spectrum_).mergeFrom(value).buildPartial();
          } else {
            spectrum_ = value;
          }
          onChanged();
        } else {
          spectrumBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public Builder clearSpectrum() {
        if (spectrumBuilder_ == null) {
          spectrum_ = edu.hyu.cs.pb.SpectrumsPB.Spectrum.getDefaultInstance();
          onChanged();
        } else {
          spectrumBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public edu.hyu.cs.pb.SpectrumsPB.Spectrum.Builder getSpectrumBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSpectrumFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      public edu.hyu.cs.pb.SpectrumsPB.SpectrumOrBuilder getSpectrumOrBuilder() {
        if (spectrumBuilder_ != null) {
          return spectrumBuilder_.getMessageOrBuilder();
        } else {
          return spectrum_;
        }
      }
      /**
       * <code>optional .Spectrum spectrum = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.hyu.cs.pb.SpectrumsPB.Spectrum, edu.hyu.cs.pb.SpectrumsPB.Spectrum.Builder, edu.hyu.cs.pb.SpectrumsPB.SpectrumOrBuilder> 
          getSpectrumFieldBuilder() {
        if (spectrumBuilder_ == null) {
          spectrumBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.hyu.cs.pb.SpectrumsPB.Spectrum, edu.hyu.cs.pb.SpectrumsPB.Spectrum.Builder, edu.hyu.cs.pb.SpectrumsPB.SpectrumOrBuilder>(
                  spectrum_,
                  getParentForChildren(),
                  isClean());
          spectrum_ = null;
        }
        return spectrumBuilder_;
      }

      // optional int32 charge = 2;
      private int charge_ ;
      /**
       * <code>optional int32 charge = 2;</code>
       */
      public boolean hasCharge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 charge = 2;</code>
       */
      public int getCharge() {
        return charge_;
      }
      /**
       * <code>optional int32 charge = 2;</code>
       */
      public Builder setCharge(int value) {
        bitField0_ |= 0x00000002;
        charge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 charge = 2;</code>
       */
      public Builder clearCharge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        charge_ = 0;
        onChanged();
        return this;
      }

      // repeated .Match matches = 3;
      private java.util.List<edu.hyu.cs.pb.ResultsPB.Match> matches_ =
        java.util.Collections.emptyList();
      private void ensureMatchesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          matches_ = new java.util.ArrayList<edu.hyu.cs.pb.ResultsPB.Match>(matches_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          edu.hyu.cs.pb.ResultsPB.Match, edu.hyu.cs.pb.ResultsPB.Match.Builder, edu.hyu.cs.pb.ResultsPB.MatchOrBuilder> matchesBuilder_;

      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public java.util.List<edu.hyu.cs.pb.ResultsPB.Match> getMatchesList() {
        if (matchesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matches_);
        } else {
          return matchesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public int getMatchesCount() {
        if (matchesBuilder_ == null) {
          return matches_.size();
        } else {
          return matchesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.Match getMatches(int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);
        } else {
          return matchesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder setMatches(
          int index, edu.hyu.cs.pb.ResultsPB.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.set(index, value);
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder setMatches(
          int index, edu.hyu.cs.pb.ResultsPB.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.set(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder addMatches(edu.hyu.cs.pb.ResultsPB.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder addMatches(
          int index, edu.hyu.cs.pb.ResultsPB.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(index, value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder addMatches(
          edu.hyu.cs.pb.ResultsPB.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder addMatches(
          int index, edu.hyu.cs.pb.ResultsPB.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder addAllMatches(
          java.lang.Iterable<? extends edu.hyu.cs.pb.ResultsPB.Match> values) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          super.addAll(values, matches_);
          onChanged();
        } else {
          matchesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder clearMatches() {
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public Builder removeMatches(int index) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.remove(index);
          onChanged();
        } else {
          matchesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.Match.Builder getMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.MatchOrBuilder getMatchesOrBuilder(
          int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);  } else {
          return matchesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public java.util.List<? extends edu.hyu.cs.pb.ResultsPB.MatchOrBuilder> 
           getMatchesOrBuilderList() {
        if (matchesBuilder_ != null) {
          return matchesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matches_);
        }
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.Match.Builder addMatchesBuilder() {
        return getMatchesFieldBuilder().addBuilder(
            edu.hyu.cs.pb.ResultsPB.Match.getDefaultInstance());
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.Match.Builder addMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().addBuilder(
            index, edu.hyu.cs.pb.ResultsPB.Match.getDefaultInstance());
      }
      /**
       * <code>repeated .Match matches = 3;</code>
       */
      public java.util.List<edu.hyu.cs.pb.ResultsPB.Match.Builder> 
           getMatchesBuilderList() {
        return getMatchesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          edu.hyu.cs.pb.ResultsPB.Match, edu.hyu.cs.pb.ResultsPB.Match.Builder, edu.hyu.cs.pb.ResultsPB.MatchOrBuilder> 
          getMatchesFieldBuilder() {
        if (matchesBuilder_ == null) {
          matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              edu.hyu.cs.pb.ResultsPB.Match, edu.hyu.cs.pb.ResultsPB.Match.Builder, edu.hyu.cs.pb.ResultsPB.MatchOrBuilder>(
                  matches_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          matches_ = null;
        }
        return matchesBuilder_;
      }

      // optional int32 spectrum_index = 4;
      private int spectrumIndex_ ;
      /**
       * <code>optional int32 spectrum_index = 4;</code>
       */
      public boolean hasSpectrumIndex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 spectrum_index = 4;</code>
       */
      public int getSpectrumIndex() {
        return spectrumIndex_;
      }
      /**
       * <code>optional int32 spectrum_index = 4;</code>
       */
      public Builder setSpectrumIndex(int value) {
        bitField0_ |= 0x00000008;
        spectrumIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 spectrum_index = 4;</code>
       */
      public Builder clearSpectrumIndex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        spectrumIndex_ = 0;
        onChanged();
        return this;
      }

      // optional .Stats stats = 5;
      private edu.hyu.cs.pb.ResultsPB.Stats stats_ = edu.hyu.cs.pb.ResultsPB.Stats.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          edu.hyu.cs.pb.ResultsPB.Stats, edu.hyu.cs.pb.ResultsPB.Stats.Builder, edu.hyu.cs.pb.ResultsPB.StatsOrBuilder> statsBuilder_;
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public boolean hasStats() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.Stats getStats() {
        if (statsBuilder_ == null) {
          return stats_;
        } else {
          return statsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public Builder setStats(edu.hyu.cs.pb.ResultsPB.Stats value) {
        if (statsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stats_ = value;
          onChanged();
        } else {
          statsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public Builder setStats(
          edu.hyu.cs.pb.ResultsPB.Stats.Builder builderForValue) {
        if (statsBuilder_ == null) {
          stats_ = builderForValue.build();
          onChanged();
        } else {
          statsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public Builder mergeStats(edu.hyu.cs.pb.ResultsPB.Stats value) {
        if (statsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              stats_ != edu.hyu.cs.pb.ResultsPB.Stats.getDefaultInstance()) {
            stats_ =
              edu.hyu.cs.pb.ResultsPB.Stats.newBuilder(stats_).mergeFrom(value).buildPartial();
          } else {
            stats_ = value;
          }
          onChanged();
        } else {
          statsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public Builder clearStats() {
        if (statsBuilder_ == null) {
          stats_ = edu.hyu.cs.pb.ResultsPB.Stats.getDefaultInstance();
          onChanged();
        } else {
          statsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.Stats.Builder getStatsBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getStatsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      public edu.hyu.cs.pb.ResultsPB.StatsOrBuilder getStatsOrBuilder() {
        if (statsBuilder_ != null) {
          return statsBuilder_.getMessageOrBuilder();
        } else {
          return stats_;
        }
      }
      /**
       * <code>optional .Stats stats = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          edu.hyu.cs.pb.ResultsPB.Stats, edu.hyu.cs.pb.ResultsPB.Stats.Builder, edu.hyu.cs.pb.ResultsPB.StatsOrBuilder> 
          getStatsFieldBuilder() {
        if (statsBuilder_ == null) {
          statsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              edu.hyu.cs.pb.ResultsPB.Stats, edu.hyu.cs.pb.ResultsPB.Stats.Builder, edu.hyu.cs.pb.ResultsPB.StatsOrBuilder>(
                  stats_,
                  getParentForChildren(),
                  isClean());
          stats_ = null;
        }
        return statsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Results)
    }

    static {
      defaultInstance = new Results(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Results)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Match_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Match_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Stats_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Stats_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Results_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Results_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rresults.proto\032\016peptides.proto\032\016spectru" +
      "m.proto\"1\n\005Match\022\r\n\005xcorr\030\001 \001(\001\022\031\n\007pepti" +
      "de\030\002 \001(\0132\010.Peptide\"8\n\005Stats\022\r\n\005count\030\001 \001" +
      "(\005\022\013\n\003sum\030\002 \001(\001\022\023\n\013sum_squares\030\003 \001(\001\"~\n\007" +
      "Results\022\033\n\010spectrum\030\001 \001(\0132\t.Spectrum\022\016\n\006" +
      "charge\030\002 \001(\005\022\027\n\007matches\030\003 \003(\0132\006.Match\022\026\n" +
      "\016spectrum_index\030\004 \001(\005\022\025\n\005stats\030\005 \001(\0132\006.S" +
      "tatsB\034\n\redu.hyu.cs.pbB\tResultsPBH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Match_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Match_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Match_descriptor,
              new java.lang.String[] { "Xcorr", "Peptide", });
          internal_static_Stats_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Stats_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Stats_descriptor,
              new java.lang.String[] { "Count", "Sum", "SumSquares", });
          internal_static_Results_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Results_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Results_descriptor,
              new java.lang.String[] { "Spectrum", "Charge", "Matches", "SpectrumIndex", "Stats", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.hyu.cs.pb.PeptidesPB.getDescriptor(),
          edu.hyu.cs.pb.SpectrumsPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
