// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: view_ms1_cmds.proto

package edu.hyu.cs.pb;

public final class ViewMS1CommandPB {
  private ViewMS1CommandPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ViewMS1CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string load = 1;
    /**
     * <code>optional string load = 1;</code>
     */
    boolean hasLoad();
    /**
     * <code>optional string load = 1;</code>
     */
    java.lang.String getLoad();
    /**
     * <code>optional string load = 1;</code>
     */
    com.google.protobuf.ByteString
        getLoadBytes();

    // optional double bucket = 2;
    /**
     * <code>optional double bucket = 2;</code>
     */
    boolean hasBucket();
    /**
     * <code>optional double bucket = 2;</code>
     */
    double getBucket();

    // optional double min_mz = 3;
    /**
     * <code>optional double min_mz = 3;</code>
     */
    boolean hasMinMz();
    /**
     * <code>optional double min_mz = 3;</code>
     */
    double getMinMz();

    // optional double max_mz = 4;
    /**
     * <code>optional double max_mz = 4;</code>
     */
    boolean hasMaxMz();
    /**
     * <code>optional double max_mz = 4;</code>
     */
    double getMaxMz();

    // optional double min_rtime = 5;
    /**
     * <code>optional double min_rtime = 5;</code>
     */
    boolean hasMinRtime();
    /**
     * <code>optional double min_rtime = 5;</code>
     */
    double getMinRtime();

    // optional double max_rtime = 6;
    /**
     * <code>optional double max_rtime = 6;</code>
     */
    boolean hasMaxRtime();
    /**
     * <code>optional double max_rtime = 6;</code>
     */
    double getMaxRtime();

    // optional string write_matrix = 7;
    /**
     * <code>optional string write_matrix = 7;</code>
     */
    boolean hasWriteMatrix();
    /**
     * <code>optional string write_matrix = 7;</code>
     */
    java.lang.String getWriteMatrix();
    /**
     * <code>optional string write_matrix = 7;</code>
     */
    com.google.protobuf.ByteString
        getWriteMatrixBytes();
  }
  /**
   * Protobuf type {@code pb.ViewMS1Command}
   */
  public static final class ViewMS1Command extends
      com.google.protobuf.GeneratedMessage
      implements ViewMS1CommandOrBuilder {
    // Use ViewMS1Command.newBuilder() to construct.
    private ViewMS1Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ViewMS1Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ViewMS1Command defaultInstance;
    public static ViewMS1Command getDefaultInstance() {
      return defaultInstance;
    }

    public ViewMS1Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ViewMS1Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              load_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              bucket_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              minMz_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              maxMz_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              minRtime_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              maxRtime_ = input.readDouble();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              writeMatrix_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.hyu.cs.pb.ViewMS1CommandPB.internal_static_pb_ViewMS1Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.hyu.cs.pb.ViewMS1CommandPB.internal_static_pb_ViewMS1Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command.class, edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command.Builder.class);
    }

    public static com.google.protobuf.Parser<ViewMS1Command> PARSER =
        new com.google.protobuf.AbstractParser<ViewMS1Command>() {
      public ViewMS1Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ViewMS1Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ViewMS1Command> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string load = 1;
    public static final int LOAD_FIELD_NUMBER = 1;
    private java.lang.Object load_;
    /**
     * <code>optional string load = 1;</code>
     */
    public boolean hasLoad() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string load = 1;</code>
     */
    public java.lang.String getLoad() {
      java.lang.Object ref = load_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          load_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string load = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLoadBytes() {
      java.lang.Object ref = load_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        load_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double bucket = 2;
    public static final int BUCKET_FIELD_NUMBER = 2;
    private double bucket_;
    /**
     * <code>optional double bucket = 2;</code>
     */
    public boolean hasBucket() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double bucket = 2;</code>
     */
    public double getBucket() {
      return bucket_;
    }

    // optional double min_mz = 3;
    public static final int MIN_MZ_FIELD_NUMBER = 3;
    private double minMz_;
    /**
     * <code>optional double min_mz = 3;</code>
     */
    public boolean hasMinMz() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double min_mz = 3;</code>
     */
    public double getMinMz() {
      return minMz_;
    }

    // optional double max_mz = 4;
    public static final int MAX_MZ_FIELD_NUMBER = 4;
    private double maxMz_;
    /**
     * <code>optional double max_mz = 4;</code>
     */
    public boolean hasMaxMz() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double max_mz = 4;</code>
     */
    public double getMaxMz() {
      return maxMz_;
    }

    // optional double min_rtime = 5;
    public static final int MIN_RTIME_FIELD_NUMBER = 5;
    private double minRtime_;
    /**
     * <code>optional double min_rtime = 5;</code>
     */
    public boolean hasMinRtime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double min_rtime = 5;</code>
     */
    public double getMinRtime() {
      return minRtime_;
    }

    // optional double max_rtime = 6;
    public static final int MAX_RTIME_FIELD_NUMBER = 6;
    private double maxRtime_;
    /**
     * <code>optional double max_rtime = 6;</code>
     */
    public boolean hasMaxRtime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional double max_rtime = 6;</code>
     */
    public double getMaxRtime() {
      return maxRtime_;
    }

    // optional string write_matrix = 7;
    public static final int WRITE_MATRIX_FIELD_NUMBER = 7;
    private java.lang.Object writeMatrix_;
    /**
     * <code>optional string write_matrix = 7;</code>
     */
    public boolean hasWriteMatrix() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string write_matrix = 7;</code>
     */
    public java.lang.String getWriteMatrix() {
      java.lang.Object ref = writeMatrix_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          writeMatrix_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string write_matrix = 7;</code>
     */
    public com.google.protobuf.ByteString
        getWriteMatrixBytes() {
      java.lang.Object ref = writeMatrix_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        writeMatrix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      load_ = "";
      bucket_ = 0D;
      minMz_ = 0D;
      maxMz_ = 0D;
      minRtime_ = 0D;
      maxRtime_ = 0D;
      writeMatrix_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLoadBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, bucket_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, minMz_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, maxMz_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, minRtime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, maxRtime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getWriteMatrixBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLoadBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, bucket_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, minMz_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, maxMz_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, minRtime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, maxRtime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getWriteMatrixBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.ViewMS1Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.hyu.cs.pb.ViewMS1CommandPB.internal_static_pb_ViewMS1Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.hyu.cs.pb.ViewMS1CommandPB.internal_static_pb_ViewMS1Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command.class, edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command.Builder.class);
      }

      // Construct using edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        load_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bucket_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        minMz_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        maxMz_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        minRtime_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        maxRtime_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        writeMatrix_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.hyu.cs.pb.ViewMS1CommandPB.internal_static_pb_ViewMS1Command_descriptor;
      }

      public edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command getDefaultInstanceForType() {
        return edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command.getDefaultInstance();
      }

      public edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command build() {
        edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command buildPartial() {
        edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command result = new edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.load_ = load_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bucket_ = bucket_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.minMz_ = minMz_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.maxMz_ = maxMz_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.minRtime_ = minRtime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.maxRtime_ = maxRtime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.writeMatrix_ = writeMatrix_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command) {
          return mergeFrom((edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command other) {
        if (other == edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command.getDefaultInstance()) return this;
        if (other.hasLoad()) {
          bitField0_ |= 0x00000001;
          load_ = other.load_;
          onChanged();
        }
        if (other.hasBucket()) {
          setBucket(other.getBucket());
        }
        if (other.hasMinMz()) {
          setMinMz(other.getMinMz());
        }
        if (other.hasMaxMz()) {
          setMaxMz(other.getMaxMz());
        }
        if (other.hasMinRtime()) {
          setMinRtime(other.getMinRtime());
        }
        if (other.hasMaxRtime()) {
          setMaxRtime(other.getMaxRtime());
        }
        if (other.hasWriteMatrix()) {
          bitField0_ |= 0x00000040;
          writeMatrix_ = other.writeMatrix_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.hyu.cs.pb.ViewMS1CommandPB.ViewMS1Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string load = 1;
      private java.lang.Object load_ = "";
      /**
       * <code>optional string load = 1;</code>
       */
      public boolean hasLoad() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string load = 1;</code>
       */
      public java.lang.String getLoad() {
        java.lang.Object ref = load_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          load_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string load = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLoadBytes() {
        java.lang.Object ref = load_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          load_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string load = 1;</code>
       */
      public Builder setLoad(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        load_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string load = 1;</code>
       */
      public Builder clearLoad() {
        bitField0_ = (bitField0_ & ~0x00000001);
        load_ = getDefaultInstance().getLoad();
        onChanged();
        return this;
      }
      /**
       * <code>optional string load = 1;</code>
       */
      public Builder setLoadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        load_ = value;
        onChanged();
        return this;
      }

      // optional double bucket = 2;
      private double bucket_ ;
      /**
       * <code>optional double bucket = 2;</code>
       */
      public boolean hasBucket() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double bucket = 2;</code>
       */
      public double getBucket() {
        return bucket_;
      }
      /**
       * <code>optional double bucket = 2;</code>
       */
      public Builder setBucket(double value) {
        bitField0_ |= 0x00000002;
        bucket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double bucket = 2;</code>
       */
      public Builder clearBucket() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bucket_ = 0D;
        onChanged();
        return this;
      }

      // optional double min_mz = 3;
      private double minMz_ ;
      /**
       * <code>optional double min_mz = 3;</code>
       */
      public boolean hasMinMz() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double min_mz = 3;</code>
       */
      public double getMinMz() {
        return minMz_;
      }
      /**
       * <code>optional double min_mz = 3;</code>
       */
      public Builder setMinMz(double value) {
        bitField0_ |= 0x00000004;
        minMz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double min_mz = 3;</code>
       */
      public Builder clearMinMz() {
        bitField0_ = (bitField0_ & ~0x00000004);
        minMz_ = 0D;
        onChanged();
        return this;
      }

      // optional double max_mz = 4;
      private double maxMz_ ;
      /**
       * <code>optional double max_mz = 4;</code>
       */
      public boolean hasMaxMz() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double max_mz = 4;</code>
       */
      public double getMaxMz() {
        return maxMz_;
      }
      /**
       * <code>optional double max_mz = 4;</code>
       */
      public Builder setMaxMz(double value) {
        bitField0_ |= 0x00000008;
        maxMz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double max_mz = 4;</code>
       */
      public Builder clearMaxMz() {
        bitField0_ = (bitField0_ & ~0x00000008);
        maxMz_ = 0D;
        onChanged();
        return this;
      }

      // optional double min_rtime = 5;
      private double minRtime_ ;
      /**
       * <code>optional double min_rtime = 5;</code>
       */
      public boolean hasMinRtime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double min_rtime = 5;</code>
       */
      public double getMinRtime() {
        return minRtime_;
      }
      /**
       * <code>optional double min_rtime = 5;</code>
       */
      public Builder setMinRtime(double value) {
        bitField0_ |= 0x00000010;
        minRtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double min_rtime = 5;</code>
       */
      public Builder clearMinRtime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        minRtime_ = 0D;
        onChanged();
        return this;
      }

      // optional double max_rtime = 6;
      private double maxRtime_ ;
      /**
       * <code>optional double max_rtime = 6;</code>
       */
      public boolean hasMaxRtime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double max_rtime = 6;</code>
       */
      public double getMaxRtime() {
        return maxRtime_;
      }
      /**
       * <code>optional double max_rtime = 6;</code>
       */
      public Builder setMaxRtime(double value) {
        bitField0_ |= 0x00000020;
        maxRtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double max_rtime = 6;</code>
       */
      public Builder clearMaxRtime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        maxRtime_ = 0D;
        onChanged();
        return this;
      }

      // optional string write_matrix = 7;
      private java.lang.Object writeMatrix_ = "";
      /**
       * <code>optional string write_matrix = 7;</code>
       */
      public boolean hasWriteMatrix() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string write_matrix = 7;</code>
       */
      public java.lang.String getWriteMatrix() {
        java.lang.Object ref = writeMatrix_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          writeMatrix_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string write_matrix = 7;</code>
       */
      public com.google.protobuf.ByteString
          getWriteMatrixBytes() {
        java.lang.Object ref = writeMatrix_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          writeMatrix_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string write_matrix = 7;</code>
       */
      public Builder setWriteMatrix(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        writeMatrix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string write_matrix = 7;</code>
       */
      public Builder clearWriteMatrix() {
        bitField0_ = (bitField0_ & ~0x00000040);
        writeMatrix_ = getDefaultInstance().getWriteMatrix();
        onChanged();
        return this;
      }
      /**
       * <code>optional string write_matrix = 7;</code>
       */
      public Builder setWriteMatrixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        writeMatrix_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pb.ViewMS1Command)
    }

    static {
      defaultInstance = new ViewMS1Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pb.ViewMS1Command)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ViewMS1Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_ViewMS1Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023view_ms1_cmds.proto\022\002pb\"\212\001\n\016ViewMS1Com" +
      "mand\022\014\n\004load\030\001 \001(\t\022\016\n\006bucket\030\002 \001(\001\022\016\n\006mi" +
      "n_mz\030\003 \001(\001\022\016\n\006max_mz\030\004 \001(\001\022\021\n\tmin_rtime\030" +
      "\005 \001(\001\022\021\n\tmax_rtime\030\006 \001(\001\022\024\n\014write_matrix" +
      "\030\007 \001(\tB#\n\redu.hyu.cs.pbB\020ViewMS1CommandP" +
      "BH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pb_ViewMS1Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pb_ViewMS1Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_ViewMS1Command_descriptor,
              new java.lang.String[] { "Load", "Bucket", "MinMz", "MaxMz", "MinRtime", "MaxRtime", "WriteMatrix", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
